# Generated by Django 3.1 on 2020-10-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbprac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='members',
            name='passwd',
            field=models.CharField(max_length=50),
        ),
    ]
