# Generated by Django 3.1 on 2020-10-05 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbprac', '0002_auto_20201006_0342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
